-- TODO:
--
-- ref: https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/material.lua
--
--
-- idk wth is that, but lets take a look: https://gitlab.com/DBotThePony/DLib/-/blob/develop/lua_src/dlib/modules/s3tc.lua?ref_type=heads
--
-- vtf? https://gitlab.com/DBotThePony/DLib/-/blob/develop/lua_src/dlib/modules/vtf.lua?ref_type=heads
-- kinda reader? https://gitlab.com/DBotThePony/DLib/-/blob/develop/lua_src/dlib/modules/textureworks.lua?ref_type=heads
